Germanium Static
================

:toc: left
:experimental:

The Germanium static package is for creating tests that revolve around
running a single browser instance at a time, in the whole test process.


def open_browser(browser="Firefox", wd=None, iframe_selector=DefaultIFrameSelector(), screenshot_folder="screenshots", scripts=list())
--------------------------------------------------------------------------------------------------------------------------------------

Open the given browser:

[source,python]
-----------------------------------------------------------------------------
open_browser("firefox")
-----------------------------------------------------------------------------

or:

[source,python]
-----------------------------------------------------------------------------
open_browser("ie")
-----------------------------------------------------------------------------

This allows also connecting to remote drivers, for example:

[source,python]
-----------------------------------------------------------------------------
open_browser("ff:http://10.2.1.1:5555/wd/hub")
-----------------------------------------------------------------------------

def close_browser()
-------------------

Close the currently running browser.

def go_to(url)
--------------

Go to the given URL, and wait for the page to load.

[source,python]
-----------------------------------------------------------------------------
go_to("http://google.com/")
-----------------------------------------------------------------------------

def type_keys(keys, selector = None)
------------------------------------

Type the keys specified into the element, or the currently active element.

[source,python]
-----------------------------------------------------------------------------
type_keys('germanium', Input('q'))
-----------------------------------------------------------------------------

def click(selector)
-------------------

Click the element with the given selector.

[source,python]
-----------------------------------------------------------------------------
click(Button('OK'))
-----------------------------------------------------------------------------

def hover(selector)
-------------------

Hover the element with the given selector.

def double_click(selector)
--------------------------

Double click the element with the given selector.

def right_click(selector)
-------------------------

Right click the element with the given selector.

def get_web_driver()
--------------------

Return the WebDriver instance the global Germanium was built around.

def get_germanium()
-------------------

Returns the currently running Germanium instance.

def S(*argv, **kwargs)
----------------------

Returns a deferred locator, using the `S`uper locator.

def iframe(target, keep_new_context = False)
--------------------------------------------

Selects the current working iframe with the `target` name.

[source,python]
-----------------------------------------------------------------------------
@iframe("editor")
def type_keys_into_editor(keys):
    type_keys(keys)

type_keys_into_editor('hello world') # will switch the iframe to 'editor' and back
click(Button("Save"))                # iframe is 'default'
-----------------------------------------------------------------------------

