Germanium Selectors
===================

:toc: left
:experimental:

In the `germanium.selectors` package there are several selectors that are already
built in order to make test writing easier.

All of the selectors extend the `germanium.selectors.AbstractSelector` class,
and the selector matching in Germanium called via S will invoke them.

Custom Selectors
----------------

You can write a new selector by extending the AbstractSelector class and implementing
the `get_selectors` method, that returns an array of selectors to be searched in the
document.

Provided Selectors
------------------

Provided selectors are just classes that are generally useful for testing, simple things
such as buttons, links or text.

=== Button(search_text = None, text = None, name = None)

Just a selector that finds a button by its label or name:

This selector will find simultaneously both `input` elements that have the
`type="button"`, but also `button` elements.

* some of the text, in either the `value` attribute if it's an `input`, either
  the text of the `button` (`search_text`)
* the text, either the `value` attribute if it's an input, either its text if
  it's an actual `button` (`text`)
* its form name (`name`)

[source,python]
-----------------------------------------------------------------------------
germanium.S(Button("Ok"))
-----------------------------------------------------------------------------

=== Input(input_name)

Just a selector that finds an input by its name.

[source,python]
-----------------------------------------------------------------------------
germanium.S(Input('q'))
-----------------------------------------------------------------------------

=== Link(search_text, text, search_href, href)

Just a selector that finds a link by either:

* some of its text content (`search_text`)
* its exact text content(`text`)
* some of its link location (`search_href`)
* its link location(`href`)

To match the first link that contains the 'test' string, someone can:

[source,python]
-----------------------------------------------------------------------------
germanium.S(Link("test"))
-----------------------------------------------------------------------------

Of course, the text and href search can be combined, so we can do,
in order to find a link that is on the `ciplogic.com` that has in the
text `testing`:

[source,python]
-----------------------------------------------------------------------------
germanium.S(Link("testing", search_href="http://ciplogic.com"))
-----------------------------------------------------------------------------

=== Text(text)

Just a selector that finds the element that contains the text in the page.

[source,python]
-----------------------------------------------------------------------------
germanium.S(Text("some text"))
-----------------------------------------------------------------------------

The selector can find the text even in formatted text. For example the previous
selector would match the parrent div in such a DOM structure:

[source,html]
-----------------------------------------------------------------------------
<div>
    some <b>text</b>
</div>
-----------------------------------------------------------------------------

